meta_product_name: "Instapixit"
meta_title: "Una iniciativa de amantes de la fotografía y las cosquillitas que compartirla trae."
meta_description: "Tus recuerdos al instante - Instapixit la forma más fácil de imprimir tus fotos"
meta_image: "cover.png" # should exist in `app/assets/images/`
